### ISSUE TITLE
Plotting anim returns just a square

### ISSUE THREAD

**Issue by Fluryji** [tpvasconcelos/mdsea#1]
I used the code mentioned in "Example" section and got also the output with errors which is below that section and the animation popped up but all I could see is a box, I'm pretty sure all the packages necessary for the basic simulation are installed, I'm using win10 64-bit, I just wanted to check the program and find out if it is useful since I'm doing something kinda similar (although not so sophisticated and not with so many great visualisation tools) for hard spheres potential and I think I could learn much from this program. So basically it plots animation but what I get is the image I pasted below - just the square, without any particles... I'm clueless as to what is wrong

![Figure_1](https://user-images.githubusercontent.com/24209256/117811220-94eb8680-b260-11eb-9900-9b2b5376c5b0.png)

**Comment by tpvasconcelos** [comment]
@Fluryji I have not looked into this codebase in a long time. I'll have a look at it later today and get back to you. I believe the setup is not very clear nor clean. I'll improve this

**Comment by tpvasconcelos** [comment]
@Fluryji I have pushed some changes that should fix your problem! There seemed to be an issue with the way matplotlib was interacting with the backend. Please make sure you have `PyQt5` installed as it should be best to visualise the matplotlib animations. Alternatively, just run this after pulling the changes
```shell
pip install -e ".[matplotlib]"
```

Let me know if this solves your problem and get in touch if you would like to know more about this project, or possibly contribute to it.
